#!/usr/bin/env ruby

class Cookz
  def self.help args
    puts "cookz commands\n\n"
    (Cookz.methods - Object.methods).each do |e|
      puts "  #{e}"
    end
  end

  def self.toc args
    recipes = `ls retete/`.split("\n")

    toc = "# rețete\n"

    recipes.each do |recipe|
      name = recipe.gsub('.md', '').gsub('_', ' ')
      toc += "\n* [#{name}](retete/#{recipe})"
    end
    toc += "\n"

    File.write('REȚETE.md', toc)
  end

  def self.publish args
    Cookz.toc args
    `git add .`
    unless `git ls-files --deleted`.empty?
      `git rm \`git ls-files --deleted\``
    end
    msg_a = args.clone
    msg_a.shift
    msg = msg_a.join(' ')
    `git commit -m "#{msg}"`
    `git push`
  end
end

cookz_methods = Cookz.methods - Object.methods

cookz_methods.each do |meth|
  begin
    throw 'wrong params' if Cookz.method(meth).parameters[0][1] != :args
  rescue
    puts "#{meth} is missing args parameter"
    exit 1
  end
end

if ARGV.length == 0 || !cookz_methods.include?(ARGV[0].to_sym)
  Cookz.help ARGV
  exit 2
end

Cookz.send(ARGV[0], ARGV)
